apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  name: vm2
  labels:
    kubevirt.io/os: RHEL7
spec:
  running: true
  template:
    metadata:
      labels:
        l1: l1-value
    spec:
      domain:
        resources:
          requests:
            memory: 8Mi
