apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  name: ovm2
spec:
  running: true
  template:
    spec:
      domain:
        devices:
        resources:
          # requests:
            # memory: 32M
